# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/code/OpenCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/code/OpenCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/code/OpenCV/CMakeFiles /home/pi/code/OpenCV//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/code/OpenCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenCV

# Build rule for target.
OpenCV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenCV
.PHONY : OpenCV

# fast build rule for target.
OpenCV/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/build
.PHONY : OpenCV/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main.cpp.s
.PHONY : main.cpp.s

main2.o: main2.cpp.o

.PHONY : main2.o

# target to build an object file
main2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main2.cpp.o
.PHONY : main2.cpp.o

main2.i: main2.cpp.i

.PHONY : main2.i

# target to preprocess a source file
main2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main2.cpp.i
.PHONY : main2.cpp.i

main2.s: main2.cpp.s

.PHONY : main2.s

# target to generate assembly for a file
main2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main2.cpp.s
.PHONY : main2.cpp.s

main3.o: main3.cpp.o

.PHONY : main3.o

# target to build an object file
main3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main3.cpp.o
.PHONY : main3.cpp.o

main3.i: main3.cpp.i

.PHONY : main3.i

# target to preprocess a source file
main3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main3.cpp.i
.PHONY : main3.cpp.i

main3.s: main3.cpp.s

.PHONY : main3.s

# target to generate assembly for a file
main3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main3.cpp.s
.PHONY : main3.cpp.s

main4.o: main4.cpp.o

.PHONY : main4.o

# target to build an object file
main4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main4.cpp.o
.PHONY : main4.cpp.o

main4.i: main4.cpp.i

.PHONY : main4.i

# target to preprocess a source file
main4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main4.cpp.i
.PHONY : main4.cpp.i

main4.s: main4.cpp.s

.PHONY : main4.s

# target to generate assembly for a file
main4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main4.cpp.s
.PHONY : main4.cpp.s

main5.o: main5.cpp.o

.PHONY : main5.o

# target to build an object file
main5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main5.cpp.o
.PHONY : main5.cpp.o

main5.i: main5.cpp.i

.PHONY : main5.i

# target to preprocess a source file
main5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main5.cpp.i
.PHONY : main5.cpp.i

main5.s: main5.cpp.s

.PHONY : main5.s

# target to generate assembly for a file
main5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main5.cpp.s
.PHONY : main5.cpp.s

main6.o: main6.cpp.o

.PHONY : main6.o

# target to build an object file
main6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main6.cpp.o
.PHONY : main6.cpp.o

main6.i: main6.cpp.i

.PHONY : main6.i

# target to preprocess a source file
main6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main6.cpp.i
.PHONY : main6.cpp.i

main6.s: main6.cpp.s

.PHONY : main6.s

# target to generate assembly for a file
main6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main6.cpp.s
.PHONY : main6.cpp.s

main7.o: main7.cpp.o

.PHONY : main7.o

# target to build an object file
main7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main7.cpp.o
.PHONY : main7.cpp.o

main7.i: main7.cpp.i

.PHONY : main7.i

# target to preprocess a source file
main7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main7.cpp.i
.PHONY : main7.cpp.i

main7.s: main7.cpp.s

.PHONY : main7.s

# target to generate assembly for a file
main7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main7.cpp.s
.PHONY : main7.cpp.s

main8.o: main8.cpp.o

.PHONY : main8.o

# target to build an object file
main8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main8.cpp.o
.PHONY : main8.cpp.o

main8.i: main8.cpp.i

.PHONY : main8.i

# target to preprocess a source file
main8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main8.cpp.i
.PHONY : main8.cpp.i

main8.s: main8.cpp.s

.PHONY : main8.s

# target to generate assembly for a file
main8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCV.dir/build.make CMakeFiles/OpenCV.dir/main8.cpp.s
.PHONY : main8.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OpenCV"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main2.o"
	@echo "... main2.i"
	@echo "... main2.s"
	@echo "... main3.o"
	@echo "... main3.i"
	@echo "... main3.s"
	@echo "... main4.o"
	@echo "... main4.i"
	@echo "... main4.s"
	@echo "... main5.o"
	@echo "... main5.i"
	@echo "... main5.s"
	@echo "... main6.o"
	@echo "... main6.i"
	@echo "... main6.s"
	@echo "... main7.o"
	@echo "... main7.i"
	@echo "... main7.s"
	@echo "... main8.o"
	@echo "... main8.i"
	@echo "... main8.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

